---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
  labels:
    app: python-webapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
      - name: python-webapp
        image: theisaacmoses/python-webapp:latest
        ports:
        - containerPort: 7000
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
